
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Dec 19 12:22:56 CET 2019
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NUMERO = 5;
  public static final int COMA = 4;
  public static final int ALL = 2;
  public static final int error = 1;
  public static final int CLL = 3;
  public static final int EOF = 0;
}

